//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBIT3J_SuperSystem_Final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditTrail
    {
        public int Login_ID { get; set; }
        public Nullable<int> Account_ID { get; set; }
        public string Activity { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual EmployeeAccount EmployeeAccount { get; set; }
    }
}
