//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBIT3J_SuperSystem_Final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payroll
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Payroll()
        {
            this.Expenses = new HashSet<Expens>();
        }
    
        public int Payroll_ID { get; set; }
        public Nullable<int> Employee_ID { get; set; }
        public Nullable<int> Department_ID { get; set; }
        public Nullable<int> Deduction_ID { get; set; }
        public Nullable<int> Salary_ID { get; set; }
        public Nullable<int> Leave_ID { get; set; }
        public Nullable<int> Attendance_ID { get; set; }
        public Nullable<System.DateTime> Attendance { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<decimal> Total_Salary { get; set; }
    
        public virtual Deduction Deduction { get; set; }
        public virtual Department Department { get; set; }
        public virtual Employee_Attendance Employee_Attendance { get; set; }
        public virtual EmployeeInformation EmployeeInformation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Expens> Expenses { get; set; }
        public virtual Leave_Request Leave_Request { get; set; }
        public virtual Salary Salary { get; set; }
    }
}
