//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBIT3J_SuperSystem_Final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Return_Item
    {
        public int Return_ID { get; set; }
        public Nullable<int> Transaction_ID { get; set; }
        public Nullable<int> Product_ID { get; set; }
        public Nullable<System.DateTime> Return_Date { get; set; }
        public Nullable<int> Quantity_Returned { get; set; }
        public string Reason { get; set; }
        public Nullable<bool> Resellable { get; set; }
        public string Customer_Name { get; set; }
    
        public virtual Product_Info Product_Info { get; set; }
        public virtual Sales_Transaction Sales_Transaction { get; set; }
    }
}
