//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBIT3J_SuperSystem_Final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales_Transaction_Details
    {
        public int Transaction_Detail_ID { get; set; }
        public Nullable<int> Transaction_ID { get; set; }
        public Nullable<int> Product_ID { get; set; }
        public Nullable<decimal> Total_Quantity { get; set; }
        public Nullable<int> Discount_ID { get; set; }
    
        public virtual Discount Discount { get; set; }
        public virtual Product_Info Product_Info { get; set; }
        public virtual Sales_Transaction Sales_Transaction { get; set; }
    }
}
