//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBIT3J_SuperSystem_Final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SSS
    {
        public int SSS_ID { get; set; }
        public Nullable<int> Employee_ID { get; set; }
        public string SSS_Number { get; set; }
        public Nullable<decimal> Contribution_Rate { get; set; }
        public Nullable<decimal> Contribution_Amount { get; set; }
    
        public virtual EmployeeInformation EmployeeInformation { get; set; }
    }
}
